/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrailersRouteImport } from './routes/trailers'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'
import { Route as ClipsIndexRouteImport } from './routes/clips.index'
import { Route as ClipsSlugRouteImport } from './routes/clips.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as TrailersIndexRouteImport } from './routes/trailers.index'
import { Route as TrailersSlugRouteImport } from './routes/trailers.$slug'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesSlugRouteImport } from './routes/vehicles.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailersRoute = TrailersRouteImport.update({
  id: '/trailers',
  path: '/trailers',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CharactersRoute,
} as any)
const ClipsIndexRoute = ClipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClipsRoute,
} as any)
const ClipsSlugRoute = ClipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClipsRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationsRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const TrailersIndexRoute = TrailersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrailersRoute,
} as any)
const TrailersSlugRoute = TrailersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrailersRoute,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesSlugRoute = VehiclesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VehiclesRoute,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRouteWithChildren
  '/clips': typeof ClipsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/guides': typeof GuidesRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trailers': typeof TrailersRouteWithChildren
  '/trending': typeof TrendingRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/characters/$slug': typeof CharactersSlugRoute
  '/clips/$slug': typeof ClipsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/characters/': typeof CharactersIndexRoute
  '/clips/': typeof ClipsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/trailers/': typeof TrailersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/clips/$slug': typeof ClipsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/characters': typeof CharactersIndexRoute
  '/clips': typeof ClipsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/news': typeof NewsIndexRoute
  '/trailers': typeof TrailersIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRouteWithChildren
  '/clips': typeof ClipsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/guides': typeof GuidesRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trailers': typeof TrailersRouteWithChildren
  '/trending': typeof TrendingRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/characters/$slug': typeof CharactersSlugRoute
  '/clips/$slug': typeof ClipsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/trailers/$slug': typeof TrailersSlugRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/characters/': typeof CharactersIndexRoute
  '/clips/': typeof ClipsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/trailers/': typeof TrailersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/characters'
    | '/clips'
    | '/contact'
    | '/dmca'
    | '/editorial-policy'
    | '/guides'
    | '/locations'
    | '/news'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/trailers'
    | '/trending'
    | '/vehicles'
    | '/videos'
    | '/characters/$slug'
    | '/clips/$slug'
    | '/guides/$slug'
    | '/locations/$slug'
    | '/news/$slug'
    | '/trailers/$slug'
    | '/vehicles/$slug'
    | '/videos/$slug'
    | '/characters/'
    | '/clips/'
    | '/guides/'
    | '/locations/'
    | '/news/'
    | '/trailers/'
    | '/vehicles/'
    | '/videos/'
    | '/api/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dmca'
    | '/editorial-policy'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/trending'
    | '/characters/$slug'
    | '/clips/$slug'
    | '/guides/$slug'
    | '/locations/$slug'
    | '/news/$slug'
    | '/trailers/$slug'
    | '/vehicles/$slug'
    | '/videos/$slug'
    | '/characters'
    | '/clips'
    | '/guides'
    | '/locations'
    | '/news'
    | '/trailers'
    | '/vehicles'
    | '/videos'
    | '/api/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/characters'
    | '/clips'
    | '/contact'
    | '/dmca'
    | '/editorial-policy'
    | '/guides'
    | '/locations'
    | '/news'
    | '/privacy-policy'
    | '/search'
    | '/terms'
    | '/trailers'
    | '/trending'
    | '/vehicles'
    | '/videos'
    | '/characters/$slug'
    | '/clips/$slug'
    | '/guides/$slug'
    | '/locations/$slug'
    | '/news/$slug'
    | '/trailers/$slug'
    | '/vehicles/$slug'
    | '/videos/$slug'
    | '/characters/'
    | '/clips/'
    | '/guides/'
    | '/locations/'
    | '/news/'
    | '/trailers/'
    | '/vehicles/'
    | '/videos/'
    | '/api/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  ClipsRoute: typeof ClipsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DmcaRoute: typeof DmcaRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LocationsRoute: typeof LocationsRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  TrailersRoute: typeof TrailersRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailers': {
      id: '/trailers'
      path: '/trailers'
      fullPath: '/trailers'
      preLoaderRoute: typeof TrailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/clips/': {
      id: '/clips/'
      path: '/'
      fullPath: '/clips/'
      preLoaderRoute: typeof ClipsIndexRouteImport
      parentRoute: typeof ClipsRoute
    }
    '/clips/$slug': {
      id: '/clips/$slug'
      path: '/$slug'
      fullPath: '/clips/$slug'
      preLoaderRoute: typeof ClipsSlugRouteImport
      parentRoute: typeof ClipsRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/trailers/': {
      id: '/trailers/'
      path: '/'
      fullPath: '/trailers/'
      preLoaderRoute: typeof TrailersIndexRouteImport
      parentRoute: typeof TrailersRoute
    }
    '/trailers/$slug': {
      id: '/trailers/$slug'
      path: '/$slug'
      fullPath: '/trailers/$slug'
      preLoaderRoute: typeof TrailersSlugRouteImport
      parentRoute: typeof TrailersRoute
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/$slug': {
      id: '/vehicles/$slug'
      path: '/$slug'
      fullPath: '/vehicles/$slug'
      preLoaderRoute: typeof VehiclesSlugRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CharactersRouteChildren {
  CharactersSlugRoute: typeof CharactersSlugRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersSlugRoute: CharactersSlugRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface ClipsRouteChildren {
  ClipsSlugRoute: typeof ClipsSlugRoute
  ClipsIndexRoute: typeof ClipsIndexRoute
}

const ClipsRouteChildren: ClipsRouteChildren = {
  ClipsSlugRoute: ClipsSlugRoute,
  ClipsIndexRoute: ClipsIndexRoute,
}

const ClipsRouteWithChildren = ClipsRoute._addFileChildren(ClipsRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface TrailersRouteChildren {
  TrailersSlugRoute: typeof TrailersSlugRoute
  TrailersIndexRoute: typeof TrailersIndexRoute
}

const TrailersRouteChildren: TrailersRouteChildren = {
  TrailersSlugRoute: TrailersSlugRoute,
  TrailersIndexRoute: TrailersIndexRoute,
}

const TrailersRouteWithChildren = TrailersRoute._addFileChildren(
  TrailersRouteChildren,
)

interface VehiclesRouteChildren {
  VehiclesSlugRoute: typeof VehiclesSlugRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesSlugRoute: VehiclesSlugRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharactersRoute: CharactersRouteWithChildren,
  ClipsRoute: ClipsRouteWithChildren,
  ContactRoute: ContactRoute,
  DmcaRoute: DmcaRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LocationsRoute: LocationsRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  TrailersRoute: TrailersRouteWithChildren,
  TrendingRoute: TrendingRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
